name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        os:  [ubuntu]
        version: ["3.8"]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: fastai/workflows/nbdev-ci@master
        with:
          version: ${{ matrix.version }}
          pre: 1
      - name: test docs build
        run: |
          nbdev_docs
          if [ -f "_docs/index.html" ]; then
            echo "docs built successfully.";
          else
            exit 1;
          fi
